export const SET_USER_ID = 'APP/SET_USER_ID';
export const SET_IS_AUTH = 'APP/SET_IS_AUTH';

export const SET_GAME_LIST = 'GAME/SET_GAME_LIST';
export const FETCH_GAME_LIST = 'GAME/FETCH_GAME_LIST';
export const FETCH_GAME_DATA = 'GAME/FETCH_GAME_DATA';
export const SET_CURRENT_GAME = 'GAME/SET_CURRENT_GAME';